name: base
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
- matplotlib
- matplotlib-base
- matplotlib-inline
- cudatoolkit=11.3.1
- numpy
- pillow
- pip=22.1.2
- python=3.9.13
- pytorch::pytorch=1.11.0=py3.9_cuda11.3_cudnn8.2.0_0
- pyg::pyg
- scipy
- ffmpeg=5.0.1
- tqdm=4.64.0
- networkx=2.5.1
- pandas
- seaborn
- scikit-learn=0.24
- jupyterlab=3.4.4
- imageio
- pip:
  - absl-py==1.2.0
  - deepchem==2.5.0
  - jax==0.2.17
  - opt-einsum==3.3.0
  - torchdrug==0.1.3
  - geomloss==0.2.5
  - tensorflow==2.9.1
